SET(PANES_FILES
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettings.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsCompany.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsCompany.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsCompany.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsVatRates.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsVatRates.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsVatRates.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsSaleAccounts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsSaleAccounts.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsSaleAccounts.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsPurchaseAccount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsPurchaseAccount.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsPurchaseAccount.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsSelfVatAccounts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsSelfVatAccounts.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsSelfVatAccounts.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsBankAccounts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsBankAccounts.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsBankAccounts.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsAmzBalanceAccounts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsAmzBalanceAccounts.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsAmzBalanceAccounts.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsJournal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsJournal.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsJournal.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsFbaCenters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsFbaCenters.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsFbaCenters.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrderFiles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrderFiles.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrderFiles.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrderApis.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrderApis.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrderApis.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneBookKeeping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneBookKeeping.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneBookKeeping.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrders.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneOrders.ui
    ${CMAKE_CURRENT_LIST_DIR}/WidgetPurchases.cpp
    ${CMAKE_CURRENT_LIST_DIR}/WidgetPurchases.h
    ${CMAKE_CURRENT_LIST_DIR}/WidgetPurchases.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneProfit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneProfit.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneProfit.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneInventory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneInventory.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneInventory.ui
)
