SET(PANES_FILES
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettings.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsCompany.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsCompany.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsCompany.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsVatRates.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsVatRates.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSettingsVatRates.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneSaleAccounts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneSaleAccounts.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneSaleAccounts.ui
    ${CMAKE_CURRENT_LIST_DIR}/PanePurchaseAccount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PanePurchaseAccount.h
    ${CMAKE_CURRENT_LIST_DIR}/PanePurchaseAccount.ui
    ${CMAKE_CURRENT_LIST_DIR}/PaneJournals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PaneJournals.h
    ${CMAKE_CURRENT_LIST_DIR}/PaneJournals.ui
)
