include(${CMAKE_CURRENT_LIST_DIR}/panes/panes.cmake)

SET(GUI_FILES
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogCompanyInfos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogCompanyInfos.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogCompanyInfos.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatNumber.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatNumber.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatNumber.ui
    ${CMAKE_CURRENT_LIST_DIR}/delegates/ComboBoxDelegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/delegates/ComboBoxDelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSaleAccount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSaleAccount.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSaleAccount.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddPurchaseAccount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddPurchaseAccount.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddPurchaseAccount.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatRate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatRate.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatRate.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddFbaCenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddFbaCenter.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddFbaCenter.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogVatParams.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogVatParams.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogVatParams.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPurchaseInvoices.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPurchaseInvoices.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPurchaseInvoices.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewOrders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewOrders.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewOrders.ui
    ${PANES_FILES}
)
