include(${CMAKE_CURRENT_LIST_DIR}/panes/panes.cmake)

SET(GUI_FILES
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogCompanyInfos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogCompanyInfos.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogCompanyInfos.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatNumber.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatNumber.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatNumber.ui
    ${CMAKE_CURRENT_LIST_DIR}/delegates/ComboBoxDelegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/delegates/ComboBoxDelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSaleAccount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSaleAccount.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSaleAccount.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddPurchaseAccount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddPurchaseAccount.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddPurchaseAccount.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatRate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatRate.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddVatRate.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddFbaCenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddFbaCenter.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddFbaCenter.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSelfEntry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSelfEntry.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAddSelfEntry.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogVatParams.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogVatParams.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogVatParams.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPurchaseInvoices.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPurchaseInvoices.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPurchaseInvoices.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAmzPayments.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAmzPayments.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogAmzPayments.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditCsvPurchases.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditCsvPurchases.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditCsvPurchases.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewOrders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewOrders.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewOrders.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewShipments.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewShipments.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogViewShipments.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditProductFilters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditProductFilters.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditProductFilters.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickShipment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickShipment.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogPickShipment.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditPurchase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditPurchase.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditPurchase.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditPurchases.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditPurchases.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogEditPurchases.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogDisplaySkus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogDisplaySkus.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogDisplaySkus.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogMapSkuRegraded.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogMapSkuRegraded.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogs/DialogMapSkuRegraded.ui
    ${PANES_FILES}
)
