SET(ORDERS_FILES
    ${CMAKE_CURRENT_LIST_DIR}/ActivitySource.h
    ${CMAKE_CURRENT_LIST_DIR}/ActivitySource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ActivitySourceType.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ActivitySourceType.h
    ${CMAKE_CURRENT_LIST_DIR}/SaleType.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SaleType.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxSource.h
    ${CMAKE_CURRENT_LIST_DIR}/Amount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Amount.h
    ${CMAKE_CURRENT_LIST_DIR}/Shipment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shipment.h
    ${CMAKE_CURRENT_LIST_DIR}/LineItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LineItem.h
    ${CMAKE_CURRENT_LIST_DIR}/Refund.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Refund.h
    ${CMAKE_CURRENT_LIST_DIR}/Order.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Order.h
    ${CMAKE_CURRENT_LIST_DIR}/Address.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Address.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileAmazonFbaInvoicing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileAmazonFbaInvoicing.h
    ${CMAKE_CURRENT_LIST_DIR}/InvoicingInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/InvoicingInfo.h
    ${CMAKE_CURRENT_LIST_DIR}/Result.h
    ${CMAKE_CURRENT_LIST_DIR}/OrderManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OrderManager.h
    ${CMAKE_CURRENT_LIST_DIR}/OrderTableAbstract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OrderTableAbstract.h
    ${CMAKE_CURRENT_LIST_DIR}/OrderTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OrderTable.h
    ${CMAKE_CURRENT_LIST_DIR}/OrderCompleteTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OrderCompleteTable.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxAmountTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxAmountTable.h
    ${CMAKE_CURRENT_LIST_DIR}/OrderAddressTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OrderAddressTable.h
    ${CMAKE_CURRENT_LIST_DIR}/OrderInvoicingTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OrderInvoicingTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ActivityUpdate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ActivityUpdate.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterApi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterApi.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterFile.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazon.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonEu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonEu.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonAmerica.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonAmerica.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemu.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemuEu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemuEu.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiCommerceHQ.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiCommerceHQ.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileAmazonVatEu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileAmazonVatEu.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileAmazonTransactions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileAmazonTransactions.h
    ${CMAKE_CURRENT_LIST_DIR}/FileImportersTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FileImportersTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ApiImportersTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ApiImportersTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ParamsTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ParamsTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileTemuOrders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileTemuOrders.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileTemuVatEu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterFileTemuVatEu.h
)
