SET(ORDERS_FILES
    ${CMAKE_CURRENT_LIST_DIR}/ActivitySource.h
    ${CMAKE_CURRENT_LIST_DIR}/ActivitySourceType.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ActivitySourceType.h
    ${CMAKE_CURRENT_LIST_DIR}/SaleType.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SaleType.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxSource.h
    ${CMAKE_CURRENT_LIST_DIR}/Amount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Amount.h
    ${CMAKE_CURRENT_LIST_DIR}/Shipment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shipment.h
    ${CMAKE_CURRENT_LIST_DIR}/LineItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/LineItem.h
    ${CMAKE_CURRENT_LIST_DIR}/Refund.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Refund.h
    ${CMAKE_CURRENT_LIST_DIR}/Order.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Order.h
    ${CMAKE_CURRENT_LIST_DIR}/Address.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Address.h
    ${CMAKE_CURRENT_LIST_DIR}/InvoicingInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/InvoicingInfo.h
    ${CMAKE_CURRENT_LIST_DIR}/Result.h
    ${CMAKE_CURRENT_LIST_DIR}/OrderManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/OrderManager.h
    ${CMAKE_CURRENT_LIST_DIR}/ActivityUpdate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ActivityUpdate.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterApi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterApi.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractImporterFile.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazon.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonEu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonEu.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonAmerica.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiAmazonAmerica.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemu.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemuEu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiTemuEu.h
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiCommerceHQ.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImporterApiCommerceHQ.h
    ${CMAKE_CURRENT_LIST_DIR}/ExceptionParamValue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ExceptionParamValue.h
)
