
set(BOOKS_FILES
    ${CMAKE_CURRENT_LIST_DIR}/Activity.h
    ${CMAKE_CURRENT_LIST_DIR}/Activity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ActivityTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ActivityTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxScheme.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxScheme.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxJurisdictionLevel.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxJurisdictionLevel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TaxResolver.h
    ${CMAKE_CURRENT_LIST_DIR}/TaxResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VatResolver.h
    ${CMAKE_CURRENT_LIST_DIR}/VatResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VatTerritoryResolver.h
    ${CMAKE_CURRENT_LIST_DIR}/VatTerritoryResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BooksAccountsSalesTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BooksAccountsSalesTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountsGroupedSalesTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountsGroupedSalesTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountPurchaseTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountPurchaseTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CompanyAddressTable.h
    ${CMAKE_CURRENT_LIST_DIR}/CompanyAddressTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CompanyInfosTable.h
    ${CMAKE_CURRENT_LIST_DIR}/CompanyInfosTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VatNumbersTable.h
    ${CMAKE_CURRENT_LIST_DIR}/VatNumbersTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VatCountries.h
    ${CMAKE_CURRENT_LIST_DIR}/JournalEntry.h
    ${CMAKE_CURRENT_LIST_DIR}/JournalEntry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseInvoiceManager.h
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseInvoiceManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/JournalTable.h
    ${CMAKE_CURRENT_LIST_DIR}/JournalTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/JournalEntryFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FbaCentersTable.h
    ${CMAKE_CURRENT_LIST_DIR}/FbaCentersTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountBankTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountBankTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountAmzBalanceTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountAmzBalanceTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountSelfVatTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountSelfVatTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BooksConnections.h
    ${CMAKE_CURRENT_LIST_DIR}/BooksConnections.cpp
    ${CMAKE_CURRENT_LIST_DIR}/EntrySelfTable.h
    ${CMAKE_CURRENT_LIST_DIR}/EntrySelfTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseInvoiceTable.h
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseInvoiceTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractBooksTable.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractBooksTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractBooksTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountBankTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BookAccountBankTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractBooksTableBank.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractBooksTableBank.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankPaypalEURTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankPaypalEURTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankPaypalUSDTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankPaypalUSDTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankStripeEURTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankStripeEURTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankStripeUSDTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankStripeUSDTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankWiseEURTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankWiseEURTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankWiseGBPTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankWiseGBPTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankWiseUSDTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankWiseUSDTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BankQontoTable.h
    ${CMAKE_CURRENT_LIST_DIR}/BankQontoTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ServiceClientManager.h
    ${CMAKE_CURRENT_LIST_DIR}/ServiceClientManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ServiceSalesBooksTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ServiceSalesBooksTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractBookSaver.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractBookSaver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BookSaverFull.h
    ${CMAKE_CURRENT_LIST_DIR}/BookSaverFull.cpp
    ${CMAKE_CURRENT_LIST_DIR}/InvoiceGenerator.h
    ${CMAKE_CURRENT_LIST_DIR}/InvoiceGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ReportGenerator.h
    ${CMAKE_CURRENT_LIST_DIR}/ReportGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SkuRegradedTable.h
    ${CMAKE_CURRENT_LIST_DIR}/SkuRegradedTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseAmzPaymentsManager.h
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseAmzPaymentsManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseAmzPaymentsTable.h
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseAmzPaymentsTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AmzPaymentSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/AmzPaymentSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ImportPriceTable.h
    ${CMAKE_CURRENT_LIST_DIR}/ImportPriceTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/UngroupedOrderTable.h
    ${CMAKE_CURRENT_LIST_DIR}/UngroupedOrderTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseControlTable.h
    ${CMAKE_CURRENT_LIST_DIR}/PurchaseControlTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SaleControlTable.h
    ${CMAKE_CURRENT_LIST_DIR}/SaleControlTable.cpp
)


